spring.application.name=DarLink
# Name of the Spring Boot application (used in logs, monitoring, etc.)


# Automatically updates the database schema based on your entities
# (good for development, avoid in production)
spring.jpa.hibernate.ddl-auto=update

# Database connection URL pulled from environment variable
spring.datasource.url=${DB_URL}

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.user.name=admin
spring.security.user.password=password

# Database username from environment variable
spring.datasource.username=${DB_USERNAME}

# Database password from environment variable
spring.datasource.password=${DB_PASSWORD}

# JDBC driver for PostgreSQL (use this instead of H2 when running Postgres)
spring.datasource.driver-class-name=org.postgresql.Driver

# Prints executed SQL queries in the console (useful for debugging)
spring.jpa.show-sql=true

# Secret key used to sign and verify JWT tokens (must stay private)
jwt.secret=${JWT_SECRET}

# Token validity duration (usually in milliseconds)
jwt.expiration=${JWT_EXPIRATION}

# Server port; defaults to 8443 if SERVER_PORT is not set
server.port=${SERVER_PORT:8080}

logging.level.org.springframework.security=DEBUG