services:
  backend:
    build: backend
    ports:
      - 8080:8080
    secrets:
      - db-password
        #environment:
      #    - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    networks:
      - darlink
    entrypoint: >
      sh -c '
      export SPRING_DATASOURCE_PASSWORD=$(cat /run/secrets/db-password | tr -d "\n") &&
      exec java -jar /app.jar
      '
  db:
    image: postgres:18
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/18/main
    networks:
      - darlink
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
volumes:
  db-data:
secrets:
  db-password:
    file: db/secrets/password.txt
networks:
  darlink:

