#To-do make build, make up and make down

# make build
build:
	docker compose -f compose.yml build

# make up
up:
	docker compose -f compose.yml up -d

# make down
down:
	docker compose -f compose.yml down -v
