services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - 1337:443
      - 5173:5173
    networks:
      - darlink
    volumes:
        - ./front-end:/app
        - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8081
    secrets:
      - db-password
    networks:
      - darlink
    env_file:
      - back-end/.env
    depends_on:
      - db
    volumes:
      - uploads-data:/app/uploads
      - db-backups:/var/backups/darlink
  db:
    #image: postgres:18
    build: db
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/
      - db-backups:/var/backups/darlink
    networks:
      - darlink
    environment:
      - POSTGRES_DB=DarLink
      - POSTGRES_USER=DarLink
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#    ports:
#      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U DarLink -d DarLink" ]
      interval: 5s
      timeout: 5s
      retries: 5
# add adminer
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8087:8080"
    depends_on:
      - db
    networks:
      - darlink


volumes:
  uploads-data:
  db-data:
  db-backups:
  node_modules:
secrets:
  db-password:
    file: db/secrets/password.txt

networks:
  darlink:

